services:
  db:
    image: postgres:latest
    container_name: solarwatch-database
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5430:5432"

  backend:
    image: "solarwatch-backend"
    build:
      context: backend
    container_name: solarwatch-backend
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8080:8080"

  frontend:
    image: "solarwatch-frontend"
    build:
      context: .
      dockerfile: frontend/express/Dockerfile
    container_name: solarwatch-frontend
    ports:
      - "3000:3000"
